### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ideogen** [laecdtu/C19DK#1]
The file "data_for_kaare2.csv" is missing.

**Comment by laecdtu** [comment]
Please read the comment in the code and in the readme file: The data is not included as we are not allowed to share this data due to GDPR. We have asked for permission to share the data and are waiting for an answer.

**Comment by ideogen** [comment]
Yeah. But if we could just have a version of the file where we could enter data it would be helpful.

**Comment by laecdtu** [comment]
OK. I've added a file where numbers are replaced with NAs: 'data_for_kaare_na.csv'.

**Comment by ideogen** [comment]
Great. Thanks a lot.

**Comment by ideogen** [comment]
Just one question. What does "instant" signify?

**Comment by laecdtu** [comment]
"Instant" is the number of hospitalized persons on that day.
