### ISSUE TITLE
Supply .Rdata from SSEIH.R

### ISSUE THREAD

**Issue by mikkelkrogsholm** [laecdtu/C19DK#2]
Thank you for putting up the code. 

Is it possible for you to supply the .Rdata outputs from the SIR-model run done in the SSEIH.R script? 

I would like to see the data output. 

Mikkel

**Comment by laecdtu** [comment]
I cannot do that as it may make it possible to recreate the input data. But I expect that SSI will have approval for sharing the data early next week and I'll share it here afterwards.
