### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by distortedMango** [laecdtu/C19DK#4]
Hi,

Is there any documentation somewhere on how to use this model? This was used in "The Cost-Effectiveness of a COVID-19 Vaccine in a Danish Context" too. 

We would like to use this model if we can find a proper documentation! 😄

**Comment by LasseEngboChr** [comment]
Thank you for the question. 
Some additional information is available in Danish:
[https://files.ssi.dk/teknisk-gennemgang-af-modellerne-10062020](https://files.ssi.dk/teknisk-gennemgang-af-modellerne-10062020)
The code was shared to document what was used in Denmark. It was produced as part of a collaborative project that has ended and it is intended to be left in the original state.
